version: '3'
services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=bob
      - MYSQL_DATABASE=base1
      - MYSQL_USER=bob
      - MYSQL_PASSWORD=bob
